apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Rediriger HTTP vers HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Forcer HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"  # Limite la taille des requêtes à 8 Mo
spec:
  rules:
  - host: enstso.com  # Remplace par ton domaine Cloudflare
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service
            port:
              number: 80