apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.enstso.com  # Redirection 301

spec:
  ingressClassName: nginx
  rules:
  - host: enstso.com  # Remplace par ton domaine
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service  # Nom de ton service Next.js
            port:
              number: 80
