apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Réécrire le chemin
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Rediriger HTTP vers HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"  # Force l'utilisation du HTTPS pour la communication backend
spec:
  ingressClassName: nginx
  rules:
  - host: enstso.com  # Remplace par ton domaine
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service  # Nom de ton service Next.js
            port:
              number: 80
